"""template categories

Revision ID: 9986e47aa520
Revises: 5a735664aa26
Create Date: 2026-10-04 17:56:34.856913+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9986e47aa520"
down_revision: str | None = "5a735664aa26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), server_default="blue", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "color IN ('blue', 'green', 'teal', 'purple', 'orange', 'red', 'yellow', 'gray')",
            name=op.f("ck_categories_color"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(
        "uq_categories_name_lower", "categories", [sa.literal_column("lower(name)")], unique=True
    )
    op.add_column("templates", sa.Column("category_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_templates_category_id"), "templates", ["category_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_templates_category_id_categories"),
        "templates",
        "categories",
        ["category_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_templates_category_id_categories"), "templates", type_="foreignkey")
    op.drop_index(op.f("ix_templates_category_id"), table_name="templates")
    op.drop_column("templates", "category_id")
    op.drop_index("uq_categories_name_lower", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
