"""runs keep template name

Revision ID: 2d3aaecd8d8f
Revises: 9986e47aa520
Create Date: 2026-10-04 19:06:59.430569+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2d3aaecd8d8f"
down_revision: str | None = "9986e47aa520"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("template_name", sa.Text(), nullable=True))
    op.alter_column("runs", "template_id", existing_type=sa.BIGINT(), nullable=True)
    op.drop_constraint(op.f("fk_runs_template_id_templates"), "runs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_runs_template_id_templates"),
        "runs",
        "templates",
        ["template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_runs_template_id_templates"), "runs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_runs_template_id_templates"), "runs", "templates", ["template_id"], ["id"]
    )
    # Runs of deleted templates have no template to point to anymore: they cannot go back
    # to NOT NULL and are removed.
    op.execute("DELETE FROM runs WHERE template_id IS NULL")
    op.alter_column("runs", "template_id", existing_type=sa.BIGINT(), nullable=False)
    op.drop_column("runs", "template_name")
    # ### end Alembic commands ###
