"""run relaunch_of

Revision ID: 5a735664aa26
Revises: 3734d2651b98
Create Date: 2026-10-04 17:26:19.498736+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5a735664aa26"
down_revision: str | None = "3734d2651b98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("relaunch_of", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_runs_relaunch_of_runs"),
        "runs",
        "runs",
        ["relaunch_of"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_runs_relaunch_of_runs"), "runs", type_="foreignkey")
    op.drop_column("runs", "relaunch_of")
    # ### end Alembic commands ###
